CREATE DATABASE '/firebird/data/pax.fdb'
USER 'SYSDBA' PASSWORD 'masterkey';

CONNECT '/firebird/data/pax.fdb'
USER 'SYSDBA' PASSWORD 'masterkey';

CREATE TABLE TEST_TABLE (
    ID INTEGER NOT NULL PRIMARY KEY,
    NAME VARCHAR(50)
);

CREATE TABLE SYNC_OUTBOX (
    ID INTEGER NOT NULL PRIMARY KEY,
    TABLE_NAME VARCHAR(50),
    OPERATION VARCHAR(10),
    PAYLOAD_AFTER BLOB SUB_TYPE TEXT,
    SEQUENCE_ID BIGINT,
    PROCESSED SMALLINT
);

INSERT INTO SYNC_OUTBOX (ID, TABLE_NAME, OPERATION, PK_VALUE, PAYLOAD_AFTER, SEQUENCE_ID)
VALUES (1, 'CLIENTES', 'INSERT', '1', '{"ID": 1, "NOME": "JOÃO SILVA", "DATA_NASC": "1990-01-01"}', 1001);

COMMIT;
QUIT;