CREATE DATABASE '/firebird/data/pax.fdb'
USER 'SYSDBA' PASSWORD 'masterkey';

-- 🔴 ESSENCIAL
CONNECT '/firebird/data/pax.fdb'
USER 'SYSDBA' PASSWORD 'masterkey';

CREATE TABLE TEST_TABLE (
    ID INTEGER NOT NULL PRIMARY KEY,
    NAME VARCHAR(50)
);

-- (opcional) tabela que seu Go espera
CREATE TABLE SYNC_OUTBOX (
    ID VARCHAR(36) NOT NULL PRIMARY KEY,
    TABLE_NAME VARCHAR(50),
    OPERATION VARCHAR(10),
    PAYLOAD_AFTER BLOB SUB_TYPE TEXT,
    SEQUENCE_ID BIGINT,
    PROCESSED SMALLINT
);

INSERT INTO SYNC_OUTBOX (
    ID, TABLE_NAME, OPERATION, PAYLOAD_AFTER, SEQUENCE_ID, PROCESSED
) VALUES (
    '11111111-1111-1111-1111-111111111111',
    'orders',
    'INSERT',
    '{"id":1,"status":"OPEN"}',
    1,
    0
);

INSERT INTO SYNC_OUTBOX (ID, TABLE_NAME, OPERATION, PK_VALUE, PAYLOAD_AFTER, SEQUENCE_ID)
VALUES (1, 'CLIENTES', 'INSERT', '1', '{"ID": 1, "NOME": "JOÃO SILVA", "DATA_NASC": "1990-01-01"}', 1001);

COMMIT;
QUIT;