CREATE DATABASE '/firebird/data/pax.fdb' USER 'SYSDBA' PASSWORD 'masterkey';

CREATE GENERATOR GEN_SYNC_OUTBOX_ID;
CREATE GENERATOR GEN_SYNC_OUTBOX_SEQ;

CREATE TABLE SYNC_OUTBOX (
    ID             INTEGER      NOT NULL PRIMARY KEY,
    TABLE_NAME     VARCHAR(64)  NOT NULL,
    OPERATION      VARCHAR(10)  NOT NULL,
    PK_VALUE       VARCHAR(255) NOT NULL,
    PAYLOAD_BEFORE BLOB SUB_TYPE TEXT,
    PAYLOAD_AFTER  BLOB SUB_TYPE TEXT,
    SEQUENCE_ID    BIGINT       NOT NULL,
    PROCESSED      SMALLINT     DEFAULT 0 NOT NULL,
    CREATED_AT     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL
);

SET TERM !! ;
CREATE TRIGGER SYNC_OUTBOX_BI FOR SYNC_OUTBOX
BEFORE INSERT AS
BEGIN
    IF (NEW.ID IS NULL) THEN NEW.ID = GEN_ID(GEN_SYNC_OUTBOX_ID, 1);
    IF (NEW.SEQUENCE_ID IS NULL) THEN NEW.SEQUENCE_ID = GEN_ID(GEN_SYNC_OUTBOX_SEQ, 1);
END!!
SET TERM ; !!

CREATE TABLE CLIENTES (
    ID INTEGER NOT NULL PRIMARY KEY,
    NOME VARCHAR(100),
    DATA_NASC TIMESTAMP
);

INSERT INTO SYNC_OUTBOX (ID, TABLE_NAME, OPERATION, PK_VALUE, PAYLOAD_AFTER, SEQUENCE_ID)
VALUES (1, 'CLIENTES', 'INSERT', '1', '{"ID": 1, "NOME": "JOAO SILVA", "DATA_NASC": "1990-01-01"}', 1001);

INSERT INTO SYNC_OUTBOX (ID, TABLE_NAME, OPERATION, PK_VALUE, PAYLOAD_AFTER, SEQUENCE_ID)
VALUES (2, 'CLIENTES', 'INSERT', '2', '{"ID": 2, "NOME": "MARIA SOUZA", "DATA_NASC": "1985-05-20"}', 1002);
COMMIT;

COMMIT;